name: joshgervais
description: "Wine Shop App"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.1
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  get_it: ^7.7.0
  # device_info_plus: ^10.1.0
  google_fonts: ^6.2.1
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.2.5
  url_launcher: ^6.2.6
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  rxdart: ^0.27.7
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  custom_navigation_bar: ^0.8.2
  dropdown_button2: ^2.3.9
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  mobile_scanner: ^5.1.1

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    
  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true

  assets:
    - assets/colors/
    - assets/icons/
    - assets/images/
